name: Go CI

on:
  push:
    branches: [ main, deploy ] 
  pull_request:
    branches: [ main, deploy ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true
    
    - name: Install dependencies
      run: go mod download 

    - name: Generate Templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.819 && templ generate

    - name: Verify code formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted correctly:"
          gofmt -s -l .
          exit 1
        fi
  
    - name: Build Web
      run: go build -v -o ./getsit-web ./cmd/web
    
    - name: Build Api
      run: go build -v -o ./getsit-api ./cmd/api

    - name: Test
      run: go test -v ./internal/... -cover

